name: Sync Upstream Source

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    name: Sync upstream to local upstream branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout empty workspace
        run: git init .

      - name: Set up Git and fetch upstream
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add upstream https://github.com/yquake2/yquake2.git
          git fetch upstream --tags

      - name: Reset upstream branch (strip workflows)
        run: |
          git checkout -B upstream upstream/master
          rm -rf .github/workflows
          git add -u
          git commit -m "Strip upstream workflows from upstream branch" || true
          git push origin upstream --force

      - name: Clean and push tags (strip workflows)
        run: |
          mkdir tmp
          for tag in $(git tag -l 'QUAKE2_*'); do
            git checkout -f $tag
            rm -rf .github/workflows
            git add -u
            git commit -m "Strip workflows from tag $tag" || true
            new_branch="tagfix-$tag"
            git checkout -b $new_branch
            git tag -f $tag
            git push origin $new_branch --force
            git push origin :refs/tags/$tag || true
            git tag -d $tag
            git tag $tag
            git push origin $tag
          done
