name: Sync Upstream Source

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync-upstream:
    name: Sync upstream to local upstream branch
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream remote and fetch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add upstream https://github.com/yquake2/yquake2.git
          git fetch upstream --tags

      - name: Create upstream branch from upstream/master
        run: |
          git checkout -B upstream upstream/master
          # Remove upstream workflow files to avoid permission issues
          rm -rf .github/workflows
          git add -u
          git commit -m "Strip upstream workflows to allow push" || true
          git push origin upstream --force

      - name: Sync tags
        run: |
          git tag -l | xargs git tag -d || true
          git fetch upstream --tags
          git push origin --tags --force
